# Generated by Django 5.2.7 on 2025-11-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.TextField(default='[]')),
                ('curret_player', models.CharField(choices=[('o', 'gracz o'), ('x', ' gracz x')], max_length=1)),
            ],
        ),
    ]
