# Generated by Django 5.2.8 on 2025-12-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0004_remove_game_user_game_guest_player_game_host_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='host_player_symbol',
            field=models.CharField(choices=[('o', 'gracz o'), ('x', ' gracz x')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
