# Generated by Django 5.2.8 on 2025-12-09 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0005_game_host_player_symbol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='curret_player',
            new_name='current_player',
        ),
    ]
