# Generated by Django 5.2.8 on 2025-12-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0006_rename_curret_player_game_current_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_player',
            field=models.CharField(choices=[('o', 'player o'), ('x', 'player x')], max_length=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='host_player_symbol',
            field=models.CharField(choices=[('o', 'player o'), ('x', 'player x')], max_length=1),
        ),
    ]
