# Generated by Django 5.2.8 on 2025-12-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0007_alter_game_current_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(choices=[('o', 'player o'), ('x', 'player x')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
